### ISSUE TITLE
Add a buzzer/beeper

### ISSUE THREAD

**Issue by MathiasSchjoedt-Bavngaard** [SWTgrp7/SWT-Assignment3-grp7#2]
Support for a hardware sound buzzer must be added, and it must be used at the end of the cooking period, sending out 3 short burst of buzzing sounds.
You are free to add further specifications – e.g. also using the buzzer in other situations during the operation and usage of the Microwave Oven, or making the buzzer have several sound effects.
You are free to specify the interface, but there probably must be a new boundary class interfacing to the hardware, in a similar way to the other hardware, e.g. the Light.

**Comment by gsglintborg** [comment]
This feature has been implemented, sending out 3 beeps when cooking is done.
Furthermore, this feature has been extended to also activate the buzzer whenever a button is pressed, so the user has some auditory feedback when operating the microwave.
